# Per-host configuration. Each key or "name" attribute is hostname. "default" hostname sets defaults for all hosts.
hosts:

  # Prototype
  hostname:

    # Maximum number of concurrent connections.
    maxConnections:       1

    # Send RSET, HELO, MAIL FROM commands after each specified count of verifications.
    resetAfterVerifications: 1

    # Close and reopen SMTP connection after specified count of verifications.
    closeAfterVerifications: ~

    # Not implemented. Close connection after specified amount of inactivity time in seconds.
    inactiveTimeout:      0

    # Non-existing user (part of email before "@") used to check if server is reliable. If server accepts non-existing email, it is unreliable.
    randomUser:           "no_such_user_iwahk1uiPoof9iCheele3eiViuCh7EipooQuoo9phai9faadoo"

    # Used for "MAIL FROM" SMTP command.
    fromEmail:            "test@example.com"

    # Used in HELO command.
    fromHost:             "localhost"

    # If set, no connections to this host will be created and all emails of this host will be marked as impossible to check by SMTP only.
    unreliable:           false
